// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLU-KGFQ9XD8OJzyg__xvkp8EdywPcWfU',
    appId: '1:236360212235:web:3106cb3e10718b78d64c0e',
    messagingSenderId: '236360212235',
    projectId: 'flutter-academy-4235e',
    authDomain: 'flutter-academy-4235e.firebaseapp.com',
    storageBucket: 'flutter-academy-4235e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSv41xbxzw7R9TdS2dbqZwDzwIeqAr9YY',
    appId: '1:236360212235:android:42f3dde6b810614fd64c0e',
    messagingSenderId: '236360212235',
    projectId: 'flutter-academy-4235e',
    storageBucket: 'flutter-academy-4235e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALTunlqnfnPLh2uTRC9WkjgygPPdmulFc',
    appId: '1:236360212235:ios:2f66e26e69112802d64c0e',
    messagingSenderId: '236360212235',
    projectId: 'flutter-academy-4235e',
    storageBucket: 'flutter-academy-4235e.appspot.com',
    iosClientId: '236360212235-glqi23sf6hcpn42r1nujboqhvnhkp3j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAcademy',
  );
}
