name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Dependencies
        working-directory: chapter10_final
        run: flutter pub get
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: chapter10_final
          baseHref: /taking-flutter-to-web/
